### PR TITLE
Can you please solved the following issues on android and IOS also?

### PR DESCRIPTION
**Pull request by harleenarora**
Error are for android:

```
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.5.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :react-native-braintree-xplat:compileDebugJavaWithJavac

Attribute application@allowBackup value=(false) from AndroidManifest.xml:11:7-34
	is also present at [:react-native-braintree-xplat] AndroidManifest.xml:14:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:7:5-117 to override.
```

I have set the validation false on android and IOS both, for get the response. 
Changes are:
**Android**: .validate(false);
**IOS**: card.shouldValidate = No;

I have solved this issue is manually but its not a better way. Validation is not working.

### CODE REVIEW

**Comment by dimaportenko** [comment]
@harleenarora why do you make PR from https://github.com/wkoutre/react-native-braintree-xplat. I don't really understand what you trying to archive. 

You can make fork of my repo and make your changes. Then do PR to this repo I'll check it.

**Comment by harleenarora** [comment]
Can you please update the library?

**Comment by dimaportenko** [comment]
what do you mean?

**Comment by harleenarora** [comment]
I mean, this library is very old. Can you update this.

**Comment by dimaportenko** [comment]
No, I'm not going to do it in the near future. Try to use https://github.com/wkoutre/react-native-braintree-xplat I think it more up to date.

**Pull request closed without merging**
